// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB19b9psIsj0TuczU5YsOfn5l5lbzjVU6A',
    appId: '1:800099032920:web:d0c678aa0a902511a9cf2d',
    messagingSenderId: '800099032920',
    projectId: 'flutter-auth-bffb6',
    authDomain: 'flutter-auth-bffb6.firebaseapp.com',
    storageBucket: 'flutter-auth-bffb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7kb6-4ppEk9-IxNSmVSaPo5cvg2UUPs',
    appId: '1:800099032920:android:e60b695f8ed9f2faa9cf2d',
    messagingSenderId: '800099032920',
    projectId: 'flutter-auth-bffb6',
    storageBucket: 'flutter-auth-bffb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmzLxvxP2J4t-9bSIJwuPhafC2tPvusH8',
    appId: '1:800099032920:ios:4c5df06a4c7622eba9cf2d',
    messagingSenderId: '800099032920',
    projectId: 'flutter-auth-bffb6',
    storageBucket: 'flutter-auth-bffb6.appspot.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmzLxvxP2J4t-9bSIJwuPhafC2tPvusH8',
    appId: '1:800099032920:ios:4c5df06a4c7622eba9cf2d',
    messagingSenderId: '800099032920',
    projectId: 'flutter-auth-bffb6',
    storageBucket: 'flutter-auth-bffb6.appspot.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
